apiVersion: tekton.dev/v1
kind: Pipeline
metadata: 
  name: pac-pipeline
spec: 
  params: 
    - default: "default message"
      description: Random Param
      name: message
      type: string
  tasks:
    - name: print-message
      params:
        - name: message
          value: $(params.message)  
      taskRef:
        name: print-message
     